export const MONTHLY_SCHEDULER_MONTH_RANGE = 3;
export const ACTIVITIES_TYPE_OPTIONS = [
  { label: "輕鬆步行", value: "WALKING" },
  { label: "太極", value: "TAI_JI" },
  { label: "伸展運動", value: "STRETCHING" },
  { label: "快步走", value: "FAST_WALK" },
  { label: "游泳", value: "SWIMMING" },
  { label: "輕鬆地騎單車", value: "RACING" },
  { label: "跑步", value: "RUNNING" },
  { label: "瑜珈", value: "YOGA" },
  { label: "高爾夫球", value: "GOLF" },
  { label: "球類運動", value: "BALL" },
  { label: "跳舞", value: "DANCE" },
  { label: "行山", value: "HIKING" },
  { label: "網球", value: "TENNIS" },
  { label: "打拳", value: "BOXING" },
];
export const ACTIVITIES_TYPE_ZH_MAP: Record<string, string> = {
  WALKING: "輕鬆步行",
  TAI_JI: "太極",
  STRETCHING: "伸展運動",
  FAST_WALK: "快步走",
  SWIMMING: "游泳",
  RACING: "輕鬆地騎單車",
  RUNNING: "跑步",
  YOGA: "瑜珈",
  GOLF: "高爾夫球",
  BALL: "球類運動",
  DANCE: "跳舞",
  HIKING: "行山",
  TENNIS: "網球",
  BOXING: "打拳",
};